Trip4P/T4P

- Frontend/src/pages/TravelStyleForm.jsx
TravelStyleForm.jsx파일 출발지 입력란 추가
- AI에서 목적지만 주어졌을 때 여행 일정을 제대로 만들지 못하는 문제 발생
- 서울을 목적지로 입력했을 때 인천 공항에서부터 시작한다는 식으로 결과 출력
> 여행 성향 입력 페이지 출발지 추가

- Frontend/src/pages/RestaurantRecommend.jsx
RestaurantRecommend.jsx 수정
여행 일정 추천받지 않고 사용자가 곧장 맛집 추천을 받았을 때를 가정.
> design: 맛집 추천 목록 페이지 UI수정

- Frontend/src/components/Header.jsx
- Frontend/src/pages/BudgetInput.jsx
- Frontend/src/pages/Main.jsx
- Frontend/src/pages/RestaurantRecommend.jsx
- Frontend/src/pages/TravelPlan.jsx
> design: 피그마와 일치하도록  ui수정

- Frontend/babel.config.js
- Frontend/eslint.config.js
- Frontend/jest.config.js
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/pages/TravelPlan.jsx
- Frontend/src/tests/Greeting.jsx
- Frontend/src/tests/Greeting.test.js
- Frontend/src/tests/TravelPlan.test.js
- Frontend/src/tests/setupTests.js
* API호출하고 데이터 받아왔을 때 각 태그에 잘 들어가는지 확인
* TravelPlan.jsx 페이지에 API 데이터 값 들어가는 것 확인
* startDate와 endDate는 아직 미확인
> test: 프론트 제스트 도입

- Frontend/jest.config.js
- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/pages/Budget.jsx
- Frontend/src/pages/TravelPlan.jsx
- Frontend/src/pages/TravelStyleForm.jsx
- Frontend/src/tests/Budget.test.js
- Frontend/src/tests/Greeting.jsx
- Frontend/src/tests/Greeting.test.js
- Frontend/src/tests/TravelPlan.test.js
- Frontend/src/tests/TravelStyleForm.test.js
- Frontend/src/tests/setupTests.js
* 로컬스토리지에 저장한 데이터 불러오기 테스트 통과
* API호출하고 response값 화면에 뿌리기 통과
> test: 여행 성향 입력, 여행 일정 추천

- Frontend/src/pages/Budget.jsx
- Frontend/src/pages/TravelPlan.jsx
- Frontend/src/pages/TravelStyleForm.jsx
> 백엔드 요청에 맞춰 API 응답, 요청 형식 수정

- .gitignore
루트 디렉토리 .gitignore에 *.py[cod] 추가
> chore: 루트 디렉토리 .gitignore

- Frontend/src/pages/Budget.jsx
> chore: API Request에 endCity 추가

- AI/routers/ai_router.py
- AI/routers/restaurant_router.py
- AI/schemas.py
- AI/services/gpt_service.py
여행 일정 생성시 리스트를 배열로 정확히 처리하도록 코드 개선
JSON 파싱 오류를 방지하기 위한 예외 처리 추가
맛집 추천 API에서 GPT 응답에 이미지 URL을 포함하도록 수정
> fix: AI schedule 포맷 문제 해결 및 맛집 추천 기능 수정

- Frontend/src/pages/BudgetInput.jsx
- Frontend/src/pages/TravelStyleForm.jsx
* react-datepicker에서 날짜를 선택했을 때 시간대 문제로 한국에서는 하루 늦춰진 날짜가 선택됨
* formatDateLocal() 함수를 만들어 올바른 날짜 선택하도록 함
> fix: 날짜 선택했을 때 하루 늦게 나오는 이슈 해결

- Frontend/src/pages/PlaceDetail.jsx
- Frontend/src/pages/TravelPlan.jsx
* placeType이 "meal", "accommodation"일 때는 가격대, 평점, 영업시간 원래대로 표시
* placeType이 "destination"일 때는 가격대, 평점, 영업시간 미표기
> feat: 일정 추천 페이지에서 장소 상세보기 눌렀을 때 API 요청, 응답 형식 변경

- Frontend/src/AppRouter.jsx
- Frontend/src/components/Header.jsx
- Frontend/src/pages/Signup.jsx
* 닉네임, 이메일, 비밀번호, 비밀번호 확인 입력창
* Header 회원가입 버튼에 Link로 이동할 수 있도록 연결
* 라우터에 Signup 추가
> feat: 회원가입 페이지 틀 제작

- Frontend/src/AppRouter.jsx
- Frontend/src/components/Header.jsx
- Frontend/src/pages/Login.jsx
* Login.jsx 생성
* Header 로그인 버튼에 로그인 페이지 링크 추가
* 라우터에 Login 페이지 추가
> feat: 로그인 페이지 틀 제작

- Frontend/src/pages/BudgetInput.jsx
* 일정 추천 안 받고 바로 예상했을 때 예산 계산 페이지의 차트 색상 생성함수 generateColors() 수정
* 파랑 계통으로 색상 생성하도록 조정
> fix: 예산 계산 차트 색상 생성 함수 파랑 계통으로 수정

- Frontend/src/pages/Budget.jsx
- Frontend/src/pages/BudgetInput.jsx
- Frontend/src/pages/Login.jsx
- Frontend/src/pages/PlaceDetail.jsx
- Frontend/src/pages/RestaurantRecommend.jsx
- Frontend/src/pages/TravelPlan.jsx
* API 호출하는 각 페이지에 http://127.0.0.1:8000 VITE_API_BASE_URL로 수정
> chore: .env에 base url 설정

- Frontend/src/pages/RestaurantDetail.jsx
- Frontend/src/pages/RestaurantRecommend.jsx
* get에서 post로 수정
* request에 placeId, companions, foodPreferences, atmospheres 추가
> chore: 맛집추천 -> 상세정보에 필요한 API 형식 get에서 post로, request body값 추가

- AI/routers/restaurant_router.py
- 추천 수 4~5개로 명확히 제한
- GPT 응답 파싱 안정성 향상
> 맛집 추천 GPT 프롬프트 개선 및 meals 기반 필터링 적용

- Frontend/src/AppRouter.jsx
- Frontend/src/pages/MyPlan.jsx
- Frontend/src/pages/TravelPlan.jsx
* localstorage에 저장된 travelplan 데이터를 보여주는 방식으로 구현
> feat: 사용자가 저장한 일정 볼 수 있는 페이지 제작

- AI/services/gpt_service.py
- AI가 반환하는 일정에서 DB에 존재하지 않는 `placeId`가 포함되는 문제를 해결
- `generate_schedule_prompt` 함수 내 프롬프트를 개선하여 AI가 반드시 제공된 장소 목록 안의 ID만 사용하도록 명시
- `clean_schedule()`에서 실제 DB에 존재하지 않는 `placeId`가 있을 경우 해당 일정 항목을 제거하도록 로직 보완
- 전체 일정 생성 흐름에서 중복 제거 → DB 매핑 → 검증 순서로 로직 안정화
> fix:placeId 유효성 검증 및 미확인 ID 제거 로직 추가

- AI/services/gpt_service.py
- 여행 일수만큼 일정이 생성되도록 프롬프트 강화
- JSON 외 텍스트 출력 금지 명시
- 출력 예시 복원
- max_tokens 2000으로 증가 (잘림 방지)
- JSON 파싱 예외 대응 로직 추가
- "Unexpected end of input" 오류 방지
- 일정 생성 누락 최소화
- AI 응답의 안정적 처리 보장
> fix: GPT 프롬프트 보완 및 JSON 파싱 안정성 강화

- Frontend/package-lock.json
- Frontend/package.json
- Frontend/src/components/Chart.jsx
- Frontend/src/pages/Budget.jsx
- Frontend/src/pages/BudgetInput.jsx
- Frontend/src/pages/RestaurantRecommend.jsx
- Frontend/src/pages/TravelPlan.jsx
* 기존 일정 추천 예산페이지 차트 디자인 유지
* 맛집 리스트 이미지 표기
* TravelPlan 다시 추천받기, 내 일정으로 담기 버튼 주석처리
> refactor: 차트 컴포넌트로 분리 및 적용

- AI/services/gpt_service.py
매일 일정 패턴(09:00 관광지→12:00 점심→15:00 관광지→18:00 저녁→21:00 숙소)과 “마지막 날엔 숙소 제외” 조건을 프롬프트에 명시
관광지2, 맛집2, 숙소1 일정으로 수정
지리적 인접성·JSON 포맷 고정 예시 포함해 AI 프롬프트 보강
> Refactor AI schedule generation

- AI/config.py
- AI/crud.py
- AI/models.py
- AI/routers/ai_router.py
- AI/schemas.py
- AI/services/gpt_service.py
- AI/services/popular_service.py
- GPT 프롬프트 예시 간소화 및 조건 최소화
- 관광지/맛집/숙소 조회 개수 축소 (속도 개선 목적)
- JSON 파싱 및 클린업 로직 개선
- 불필요한 중복 제거 및 구조 단순화
- gpt_service.py, ai_router.py 리팩토링
- 예상 속도: 평균 20s → 개선된 구조 기반
>  AI 일정 추천 최적화: GPT 속도 개선 및 프롬프트 단순화
